//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permisos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_operaciones
    {
        public int id { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idOperaciones { get; set; }
    
        public virtual operaciones operaciones { get; set; }
        public virtual rol rol { get; set; }
    }
}
